import { Navbar } from '@/components/Navbar'
import ThemeRegistry from '../components/ThemeRegistry/ThemeRegistry'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Vehicle Tacking',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen w-screen">
        <ThemeRegistry>
          <Navbar />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  )
}
